push cmd

diff --git a/cmd/run-all b/cmd/run-all
--- a/cmd/run-all
+++ b/cmd/run-all
@@ -1,5 +1,8 @@
 #!/bin/bash
 
+echo "************** RUN ALL ***************"
+echo ""
+
 # get parameters
 if ([ $# -lt 5 ]) || ([ $# -eq 1 ] && [ "$1" == "-h" -o "$1" == "--help" ]); then
   echo "run-all <reg username> <reg password> <k8s-context> <profile> <root directory>"
@@ -19,6 +22,23 @@ context=$3
 profile=$4
 basedir=$5
 
+# download shell if it's not exists
+cmdpath=${basedir}/cicd/cmd
+which ${cmdpath}/dn-utils 2> /dev/null
+if [ $? -eq 1 ]; then
+	mkdir -p ${cmdpath} 2> /dev/null
+	wget -O ${cmdpath}/dn-utils https://happycloudpak.github.io/cicd-template/cmd/dn-utils
+	if [ $? -eq 1 ]; then
+		echo "CAN'T download ${cmdpath}/dn-utils"
+		exit 1
+	fi
+fi
+
+# download other shells and templates
+${cmdpath}/dn-utils cmd/build-image,cmd/clear-all,cmd/deploy,cmd/read-config,cmd/set-env ${cmdpath}
+${cmdpath}/dn-utils dockerfile/Dockerfile ${basepath}/cicd
+${cmdpath}/dn-utils deploy/deploy.yaml ${basepath}/cicd
+
 # build artifactory
 ${basedir}/mvnw clean package
 if [ $? -eq 1 ]; then exit 2; fi
@@ -32,4 +52,5 @@ ${basedir}/cicd/cmd/deploy ${context} ${profile} ${basedir}
 if [ $? -eq 1 ]; then exit 2; fi
 
 echo ""
+echo "************** END ALL ***************"
 exit 0
